/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sm1yle (https://sketchfab.com/Sm1yle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wicker-basket-and-apple-284e1fdc962f49a6a57596f60fe78451
Title: Wicker Basket And Apple
*/
import * as THREE from "three";
import React, { useEffect, useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import scene from "../models/wicker_basket_and_apple.glb"
 function Model(props) {
  const { nodes, materials } = useGLTF(scene);
  const texture = useTexture(props.item.img)
//   useEffect(()=>{
//   Object.entries(materials).map((material)=>{
//     if (material.hasOwnProperty('Material.004')) {
//         // Access Material.004 and modify its properties
//         const appleMaterial = material['Material.004'];
//         // For example, you can change its color
//         appleMaterial.color= new THREE.color(props.item.color[0]);
//          // Ensure the update takes effect
//          appleMaterial.needsUpdate = true;
//       }
      
//   })
//   },[materials,props.item])

useEffect(() => {
    // Check if Material.004 exists
    if (materials['Material.004']) {
      // Access Material.004 and modify its properties
      const appleMaterial = materials['Material.004'];
      // For example, you can change its color
      appleMaterial.color = new THREE.Color(props.item.color[0]);
      // Ensure the update takes effect
      appleMaterial.needsUpdate = true;
    }
  }, [materials, props.item]);
  return (
    
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['Material.003']}
        position={[0.028, -0.121, 0.15]}
        scale={0.228}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials['Material.003']}
        position={[0.64, 2.168, 0.001]}
        scale={0.086}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials['Material.004']}
        position={[0.002, -1.22, -1.975]}
        scale={0.981}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials['Material.004']}
        position={[-1.179, -0.92, -0.139]}
        scale={1.086}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials['Material.004']}
        position={[0.995, -0.92, 0.292]}
        scale={1.123}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials['Material.004']}
        position={[-1.211, -0.92, 1.857]}
        scale={1.121}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials['Material.004']}
        position={[2.102, -0.92, 2.272]}
        scale={1.197}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials['Material.004']}
        position={[3.202, -0.707, 0.676]}
        scale={0.887}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials['Material.004']}
        position={[2.708, -0.069, -0.991]}
        rotation={[0, -1.512, 0]}
        scale={0.983}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials['Material.004']}
        position={[0.248, -0.92, 2.914]}
        scale={0.926}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials['Material.004']}
        position={[-0.483, 0.094, -2.113]}
        scale={0.998}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials['Material.004']}
        position={[-1.684, 0.399, -0.244]}
        scale={1.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials['Material.004']}
        position={[0.528, 0.399, 0.194]}
        scale={1.143}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials['Material.004']}
        position={[-1.717, 0.399, 1.786]}
        scale={1.141}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials['Material.004']}
        position={[1.654, 0.399, 2.209]}
        scale={1.218}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        material={materials['Material.004']}
        position={[2.774, 0.616, 0.584]}
        scale={0.903}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        material={materials['Material.004']}
        position={[1.461, 0.973, -1.111]}
        rotation={[0, -1.512, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials['Material.004']}
        position={[-0.232, 0.399, 2.862]}
        scale={0.942}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={materials['Material.004']}
        position={[-1.621, 1.55, -1.685]}
        rotation={[0, 0.511, 0]}
        scale={1.054}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        material={materials['Material.004']}
        position={[-1.762, 1.872, 0.657]}
        rotation={[0, 0.511, 0]}
        scale={1.167}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        material={materials['Material.004']}
        position={[0.501, 2.281, -0.082]}
        rotation={[1.092, 0.076, -0.382]}
        scale={1.207}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_46.geometry}
        material={materials['Material.004']}
        position={[-0.744, 1.933, 2.544]}
        rotation={[0, 0.511, 0]}
        scale={1.205}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        material={materials['Material.004']}
        position={[2.881, 2.3, 0.263]}
        rotation={[0, 0.511, 0]}
        scale={1.286}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_50.geometry}
        material={materials['Material.004']}
        position={[2.377, 1.461, -1.839]}
        rotation={[0, 0.511, 0]}
        scale={0.953}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_52.geometry}
        material={materials['Material.004']}
        position={[0.687, 1.216, -2.429]}
        rotation={[0, -1.001, 0]}
        scale={1.056}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_54.geometry}
        material={materials['Material.004']}
        position={[1.473, 2.33, 2.768]}
        rotation={[0, 0.511, 0]}
        scale={0.995}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_56.geometry}
        material={materials['Material.003']}
        position={[4.663, 2.106, 0.503]}
        rotation={[-1.587, 0, 0]}
        scale={0.499}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_58.geometry}
        material={materials['Material.003']}
        position={[4.663, 2.13, 0.316]}
        rotation={[-1.587, 0, 0]}
        scale={0.499}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_60.geometry}
        material={materials['Material.003']}
        position={[4.663, 2.13, 0.142]}
        rotation={[-1.587, 0, 0]}
        scale={0.499}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_62.geometry}
        material={materials['Material.003']}
        position={[-3.724, 2.106, 0.438]}
        rotation={[-1.587, 0, 0]}
        scale={0.499}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_64.geometry}
        material={materials['Material.003']}
        position={[-3.724, 2.13, 0.251]}
        rotation={[-1.587, 0, 0]}
        scale={0.499}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_66.geometry}
        material={materials['Material.003']}
        position={[-3.724, 2.13, 0.077]}
        rotation={[-1.587, 0, 0]}
        scale={0.499}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_68.geometry}
        material={materials['Material.003']}
        position={[4.755, 2.823, 0.294]}
        rotation={[0.025, 0, -Math.PI]}
        scale={[-0.252, 0.252, 0.252]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_70.geometry}
        material={materials['Material.003']}
        position={[4.755, 2.728, 0.294]}
        rotation={[0.025, 0, -Math.PI]}
        scale={[-0.252, 0.252, 0.252]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_72.geometry}
        material={materials['Material.003']}
        position={[-3.767, 2.823, 0.294]}
        rotation={[0.025, 0, -Math.PI]}
        scale={[-0.252, 0.252, 0.252]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_74.geometry}
        material={materials['Material.003']}
        position={[-3.767, 2.728, 0.294]}
        rotation={[0.025, 0, -Math.PI]}
        scale={[-0.252, 0.252, 0.252]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_76.geometry}
        material={materials['Material.003']}
        position={[0.478, -0.1, 0.209]}
        scale={0.044}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_78.geometry}
        material={materials['Material.003']}
        position={[0.478, 1.517, 0.209]}
        rotation={[0, -0.112, 0]}
        scale={0.044}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_80.geometry}
        material={materials['Material.003']}
        position={[0.478, 1.127, 0.209]}
        rotation={[0, 0.109, 0]}
        scale={0.044}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_82.geometry}
        material={materials['Material.003']}
        position={[0.478, 0.729, 0.209]}
        rotation={[0, -0.112, 0]}
        scale={[0.044, 0.04, 0.044]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_84.geometry}
        material={materials['Material.003']}
        position={[0.478, 0.366, 0.209]}
        rotation={[0, 0.109, 0]}
        scale={[0.044, 0.04, 0.044]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_86.geometry}
        material={materials['Material.003']}
        position={[0.478, -0.001, 0.209]}
        rotation={[0, -0.112, 0]}
        scale={0.044}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_88.geometry}
        material={materials['Material.003']}
        position={[0.478, -0.422, 0.209]}
        rotation={[0, 0.109, 0]}
        scale={0.044}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_90.geometry}
        material={materials['Material.003']}
        position={[0.478, -0.814, 0.209]}
        rotation={[0, -0.112, 0]}
        scale={0.044}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_92.geometry}
        material={materials['Material.003']}
        position={[0.478, -1.226, 0.209]}
        rotation={[0, 0.109, 0]}
        scale={0.044}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_94.geometry}
        material={materials['Material.003']}
        position={[0.478, -1.632, 0.209]}
        rotation={[0, -0.112, 0]}
        scale={0.043}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_96.geometry}
        material={materials['Material.003']}
        position={[0.478, -2.083, 0.209]}
        rotation={[0, 0.109, 0]}
        scale={0.043}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_98.geometry}
        material={materials['Material.003']}
        position={[0.474, -2.336, 0.231]}
        rotation={[0, -0.219, 0]}
        scale={0.507}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_100.geometry}
        material={materials['Material.003']}
        position={[0.474, -2.336, 0.231]}
        scale={0.507}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_102.geometry}
        material={materials['Material.003']}
        position={[0.474, -2.336, 0.231]}
        rotation={[0, 0.239, 0]}
        scale={0.507}
      />
    </group>
  )
}
export default Model
useGLTF.preload(scene)



